pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    inputs:
      versionSpec: 'v1.19.0'

  # install dependencies
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    inputs:
      Arguments: 'install'
    env:
      BERRY_TOKEN: $(berry.token)
    displayName: yarn install

  # Test
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    env:
      CI: true
      BERRY_TOKEN: $(berry.token)
    inputs:
      Arguments: 'ci'
    displayName: yarn ci

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: test-report.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/coverage/cobertura-coverage.xml
      reportDirectory: $(Build.SourcesDirectory)/coverage/lcov-report

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

  - task: CredScan@3
