nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthIdent: '${BERRY_TOKEN}'

npmRegistryServer: 'https://pkgs.dev.azure.com/msrp-essex/_packaging/essex-npm/npm/registry'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.1.1.cjs
